version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/webapp
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/webapp.sh
      timeout: 300
      runas: root
  
  ValidateService:
    - location: scripts/validate_application.sh
      timeout: 300