apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2022-08-31T15:48:59Z'
  labels:
    app: simple-webapp-docker
  name: simple-webapp-docker
  namespace: eazytraining
  resourceVersion: '24851'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/eazytraining/buildconfigs/simple-webapp-docker
  uid: 6d97c39a-2944-11ed-ae20-080027dad590
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-webapp-docker:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/ulrichmonji/simple-webapp-docker.git'
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          172.30.1.1:5000/openshift/python@sha256:ac50754646f0d37616515fb30467d8743fb12954260ec36c9ecb5a94499447e0
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 9778b874a8569b1e
      type: Generic
    - github:
        secret: 886b36db7dc0bb84
      type: GitHub
status:
  lastVersion: 2
