apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-webapp-docker
  name: simple-webapp-docker
  namespace: eazytraining
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: simple-webapp-docker
  sessionAffinity: None
  type: ClusterIP
