apiVersion: apps/v1
kind: Deployment
metadata:
  name: bench-deployment
  labels:
    app: bench
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: bench
  template:
    metadata:
      labels:
        app: bench
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://service-apache:9080; done"