apiVersion: v1
kind: Service
metadata:
  name: eks-devops-nodeport-service
  labels:
    app: eks-<prenom>-devops   
spec:
  type: LoadBalancer
  selector:
     app: eks-<prenom>-devops
  ports:
    - port: 80
      targetPort: 80
